from manim import *

class Demo_1(Scene):
    def construct(self):
        plane = NumberPlane()
        for i in plane.submobjects:
            i.set_opacity(0.3)
        self.play(Create(plane))
        self.wait()

        s = Square()
        self.play(Create(s))
        self.wait()
        self.play(s.animate.scale(2))
        self.wait()
        self.play(Uncreate(s))
        self.wait()

        c = Circle()
        self.play(Create(c))
        self.wait()
        self.play(c.animate.scale(2))
        self.wait()
        self.play(Uncreate(c))
        self.wait()

        a = Arc()
        self.play(Create(a))
        self.wait()
        self.play(a.animate.become(Arc(radius=2)))
        self.wait()
        self.play(a.animate.become(Arc(radius=2, start_angle=-TAU / 4)))
        self.wait()
        self.play(a.animate.become(Arc(radius=2, start_angle=-TAU / 4, angle=TAU / 2)))
        self.wait(5)
        self.play(a.animate.become(Arc(radius=2, start_angle=-TAU / 4, angle=TAU / 2, arc_center=LEFT)))
        self.wait()
        self.play(Uncreate(a))
        self.wait()

        r = Rectangle()
        self.play(Create(r))
        self.wait()
        self.play(r.animate.stretch_to_fit_height(4).stretch_to_fit_width(2))
        self.wait()
        self.play(Uncreate(r))
        self.wait()

        t = Triangle()
        self.play(Create(t))
        self.wait()
        self.play(Uncreate(t))
        self.wait()

        p = Polygon(LEFT, RIGHT, UP, UL)
        self.play(Create(p))
        self.wait()
        self.play(Uncreate(p))
        self.wait(5)


        l = Line()
        self.play(Create(l))
        self.wait()
        self.play(l.animate.become(Line(buff=0.2)))
        self.wait()
        self.play(l.animate.become(Line(path_arc=PI)))
        self.wait()
        self.play(l.animate.become(Line(path_arc=-PI)))
        self.wait()
        self.play(Uncreate(l))
        self.wait()

        ar = Arrow()
        self.play(FadeIn(ar, scale=0.01))
        self.wait()
        self.play(ar.animate.become(Arrow(buff=0)))
        self.wait()
        self.play(FadeOut(ar, scale=0.01))
        self.wait(5)


        d = Dot()
        self.play(Create(d))
        self.wait()
        self.play(Uncreate(d))
        self.wait()


        e = Ellipse().move_to(UP*3.4)
        an = Annulus().scale(0.5).move_to(UP*1.5)
        se = Sector().scale(2).move_to(DOWN*0.5)
        anse = AnnularSector().move_to(DOWN*2.9)
        for i in [e, an, se, anse]:
            self.play(Create(i))
            self.wait()
        self.play(Uncreate(VGroup(e, an, se, anse)))
        self.wait()

class Demo_2(Scene):
    def construct(self):
        plane = NumberPlane()
        for i in plane.submobjects:
            i.set_opacity(0.3)
        self.add(plane)
        m = ManimBanner().scale(0.5)
        self.play(Create(m))
        self.wait()
        self.play(m.animate.move_to([1, 1, 0]))
        self.wait()
        self.play(m.animate.shift([-1, -1, 0]))
        self.wait(3)


        # 涉及到scale
        self.play(m.animate.scale(0.5))
        self.wait(3)
        point1 = Dot([2, -1, 0], color=YELLOW)
        self.play(FadeIn(point1))
        self.play(m.animate.scale(2, about_point=[2, -1, 0]))
        self.wait(3)
        self.play(FadeOut(point1))
        self.wait()
        point2 = Dot(m.get_left(), color=PINK)
        self.play(FadeIn(point2))
        self.play(m.animate.scale(0.5, about_edge=LEFT))
        self.wait()
        self.play(FadeOut(point2))
        self.wait()
        point3 = Dot(m.get_center(), color=RED)
        self.play(FadeIn(point3))
        self.play(m.animate.scale(2))
        self.wait(3)
        self.play(FadeOut(m, point3))
        self.wait()


        # 内接圆形
        c = Circle()
        t = Triangle()
        self.play(FadeIn(c, t))
        self.wait(3)
        self.play(c.animate.scale(2), t.animate.scale(2))
        self.wait()
        self.play(c.animate.scale(0.5), t.animate.scale(0.5))
        cc = Dot(c.get_center(), color=c.get_color())
        tc = Dot(t.get_center(), color=t.get_color())
        self.wait()
        self.play(FadeIn(cc, tc))
        self.wait()
        self.play(FadeOut(*self.mobjects))
        self.wait()
